### ISSUE TITLE
Cannot install for python 3.5

### ISSUE THREAD

**Issue by BenGHolmes** [Maratyszcza/confu#3]
I'm unable to get an installation working with Python 3.5. I tried to install using:
```
pip install --upgrade git+https://github.com/Maratyszcza/confu
```
This installed correctly, but when I try to import from python3 I get `module not found`. From reading other issues I was told that I may have installed it with python2.7 instead, but my virtual environment only has python 3 so this isn't the issue. 

I then tried:
```
pip3 install --upgrade git+https://github.com/Maratyszcza/confu
```
which gave me `ImportError: No module named 'six'` despite six already being installed. Any tips on how I can get this working would be greatly appreciated.

**Comment by Maratyszcza** [comment]
It seems that you have several Python and `pip` versions installed, and they have different packages installed. I suggest you do
```
pip3 install --upgrade six
pip3 install --upgrade git+https://github.com/Maratyszcza/confu
```

**Comment by BenGHolmes** [comment]
Oh ok. I think I was getting confused because pip -V and pip3 -V pointed to the same path `/home/pi/.virtualenvs/cv/lib/python3.5/site-packages/pip (python 3.5)`. Can I still have weird install problems caused by different versions of pip if they point to the same place? I tried running the above and got:
```
HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff(from https://www.piwheels.org/simple/pyyaml/) 
Could not install requirement PyYAML from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from confu==0.0.1) because of error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl 
Could not install requirement PyYAML from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from confu==0.0.1) because of HTTP error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl for URL https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
```

As a short term fix, I was able to run the config file using python2.7 and that didn't seem to affect the install for me
